package routes

import (
	"github.com/gin-gonic/gin"
	"github.com/w3-server/middleware/jwt"
	"github.com/w3-server/routes/api"
)

func InitRouter() *gin.Engine {
	// gin.SetMode(gin.ReleaseMode)
	gin.SetMode(gin.DebugMode)

	r := gin.New()
	// r.Use(gin.Logger())
	r.Use(gin.Recovery())

	public := r.Group("/api/un")
	{
		public.GET("/ping", api.Ping)
		public.GET("/mixin/msg/pending", api.Ping)
		public.GET("/mixin/msg/pending/check/done", api.Ping)
		public.GET("/mixin/msg/send", api.Ping)
		public.GET("/schedule_init", api.Ping)
		public.GET("/weauth", api.Ping)
		public.GET("/weauth/sk", api.Ping)
		public.GET("/swg/auth/check", api.Ping)
		public.GET("/wechat/login", api.Ping)
		public.GET("/avatars", api.Ping)
		public.GET("/withdraw/fee", api.Ping)
		public.GET("/wgt", api.Ping)
		public.GET("/wgt/status", api.Ping)
		public.GET("/wgt/tx", api.Ping)
		public.GET("/wgt/to/eth", api.Ping)
		public.GET("/mixin/tx", api.Ping)
		public.GET("/point", api.Ping)
		public.GET("/wgt/price", api.Ping)
		public.GET("/topic/list", api.Ping)
		public.GET("/topic/talk/list", api.Ping)
		public.GET("/group", api.Ping)
		public.GET("/group/preview", api.Ping)
		public.GET("/group/list", api.Ping)
		public.GET("/topic", api.Ping)
		public.GET("/topic/status", api.Ping)
		public.GET("/user/info", api.Ping)
		public.GET("/img", api.Ping)
		public.POST("/phone/code", api.Ping)
		public.POST("/email/code", api.Ping)
		public.POST("/phone", api.Ping)
		public.POST("/change/pwd", api.Ping)
		public.POST("/mixin/auth/check", api.Ping)
		public.POST("/oss/callback", api.Ping)
		public.POST("/github_oauth", api.Ping)
		public.POST("/mixin_oauth", api.Ping)

	}

	admin := r.Group("/api/admin")
	admin.Use(jwt.JWT())
	{

		admin.GET("/mixin/assets", api.Ping)
		admin.GET("/mixin/flow", api.Ping)
		admin.GET("/topic/home/pending", api.Ping)
		admin.GET("/user", api.Ping)
		admin.GET("/topic", api.Ping)
		admin.GET("/wgtaddr/uid", api.Ping)
		admin.GET("/user/num", api.Ping)
		admin.GET("/verify/list", api.Ping)
		admin.GET("/mixin_check", api.Ping)
		admin.GET("/ethWallet/list", api.Ping)
		admin.GET("/all/wgt/balance", api.Ping)
		admin.GET("/wgt/withdraw/list", api.Ping)
		admin.GET("/wgt/withdraw/balance", api.Ping)
		admin.GET("/wgt/withdraw/sync", api.Ping)
		admin.GET("/group", api.Ping)
		admin.GET("/abuse/list", api.Ping)
		admin.GET("/group/num", api.Ping)

		admin.POST("/mixin/transfer", api.Ping)
		admin.POST("/topic/public/base", api.Ping)
		admin.POST("/ban/user", api.Ping)
		admin.POST("/unban/user", api.Ping)
		admin.POST("/ban/group", api.Ping)
		admin.POST("/user/modify", api.Ping)
		admin.POST("/user/verify", api.Ping)
		admin.POST("/user/change", api.Ping)
		admin.POST("/name/reset", api.Ping)
		admin.POST("/limit/clear", api.Ping)
		admin.POST("/abuse/check", api.Ping)
		admin.POST("/topic/lock", api.Ping)
		admin.POST("/group/rcd", api.Ping)
		admin.POST("/mixin/flow", api.Ping)
		admin.POST("/group/new", api.Ping)
		admin.POST("/wgt/withdraw", api.Ping)
		admin.POST("/msg/send", api.Ping)

	}

	group := r.Group("/api/group")
	group.Use(jwt.JWT())
	{
		group.GET("/share", api.Ping)
		group.GET("/invite/self", api.Ping)
		group.GET("/invite/status", api.Ping)
		group.GET("", api.Ping)
		group.GET("/upload/check", api.Ping)
		group.GET("/file/download", api.Ping)
		group.GET("/join/mixin/callback", api.Ping)
		group.GET("/list", api.Ping)
		group.GET("/private/list", api.Ping)
		group.GET("/created/num", api.Ping)
		group.GET("/newnum", api.Ping)
		group.GET("/newnum/check", api.Ping)
		group.GET("/manager/list", api.Ping)
		group.GET("/pin", api.Ping)
		group.GET("/user/abuse", api.Ping)
		group.GET("/join/mixin/price", api.Ping)
		group.GET("/join/check", api.Ping)
		group.GET("/join/user", api.Ping)
		group.GET("/join/user/num", api.Ping)
		group.GET("/post/tid", api.Ping)
		group.GET("/self/grant", api.Ping)
		group.GET("/self/grant/status", api.Ping)
		group.GET("/post/list", api.Ping)
		group.GET("/spinvite/list", api.Ping)
		group.GET("/topic/edit", api.Ping)
		group.GET("/topic/list", api.Ping)
		group.GET("/user/topic", api.Ping)
		group.POST("/join", api.Ping)
		group.POST("/new/check", api.Ping)
		group.POST("/user/role", api.Ping)
		group.POST("/transfer", api.Ping)
		group.POST("/invite/check", api.Ping)
		group.POST("/delete", api.Ping)
		group.POST("/spinvite/create", api.Ping)
		group.POST("/spinvite/delete", api.Ping)
		group.POST("/user/abuse", api.Ping)
		group.POST("/new", api.Ping)
		group.POST("/leave", api.Ping)
		group.POST("/pin", api.Ping)
		group.POST("/name", api.Ping)
		group.POST("/avatar", api.Ping)
		group.POST("/info", api.Ping)
		group.POST("/msg/send", api.Ping)
		group.POST("/payment", api.Ping)
		group.POST("/post/save", api.Ping)
		group.POST("/post/delete", api.Ping)
		group.POST("/post/pub", api.Ping)
		group.POST("/file/top", api.Ping)
		group.POST("/file/desc", api.Ping)
		group.POST("/file/delete", api.Ping)
	}

	user := r.Group("/api")
	user.Use(jwt.JWT())
	{
		user.GET("/info", api.Ping)
		user.GET("/mixin/assets", api.Ping)
		user.GET("/mixin/assets/inner", api.Ping)
		user.GET("/pending/wgt", api.Ping)
		user.GET("/day/checkin", api.Ping)
		user.GET("/msg", api.Ping)
		user.GET("/vote/list", api.Ping)
		user.GET("/msg/num", api.Ping)
		user.GET("/history", api.Ping)
		user.GET("/update/avatar", api.Ping)
		user.GET("/wgt/withdraw/list", api.Ping)
		user.GET("/balance", api.Ping)
		user.POST("/name", api.Ping)
		user.POST("/invite/redo", api.Ping)
		user.POST("/payment", api.Ping)
		user.POST("/phone/code", api.Ping)
		user.POST("/phone/verify", api.Ping)
		user.POST("/email/invite", api.Ping)
		user.POST("/email/code", api.Ping)
		user.POST("/swg/auth", api.Ping)
		user.POST("/email/verify", api.Ping)
		user.POST("/mixin/withdraw", api.Ping)
		user.POST("/wgt/withdraw", api.Ping)
		user.POST("/pwd/verify", api.Ping)
		user.POST("/verify", api.Ping)
		user.POST("/msg", api.Ping)
	}

	other := r.Group("/api")
	other.Use(jwt.JWT())
	{
		other.GET("/oss/sign/upload", api.Ping)
		other.GET("/search", api.Ping)
		other.GET("/invite/point", api.Ping)
		other.GET("/invite/point/withdraw", api.Ping)
		other.GET("/event/blockchain/vote", api.Ping)
		other.GET("/event/blockchain/vote/map", api.Ping)
		other.GET("/auth/renew", api.Ping)
		other.GET("/topic", api.Ping)
		other.GET("/topic/list", api.Ping)
		other.GET("/topic/boon/take", api.Ping)
		other.GET("/self/topic/num", api.Ping)
		other.GET("/self/topic/list", api.Ping)
		other.GET("/topic/vote", api.Ping)
		other.GET("/topic/support/callback", api.Ping)
		other.GET("/wgt/recharge/callback", api.Ping)
		other.GET("/topic/talk/list", api.Ping)

		other.POST("/mixin/auth/check", api.Ping)
		other.POST("/oss/delete", api.Ping)
		other.POST("/abuse", api.Ping)
		other.POST("/topic/delete", api.Ping)
		other.POST("/topic/support", api.Ping)
		other.POST("/topic/vote", api.Ping)
		other.POST("/topic/collect", api.Ping)
		other.POST("/topic/attr", api.Ping)
		other.POST("/talk/post", api.Ping)
		other.POST("/talk/reply", api.Ping)
		other.POST("/talk/delete", api.Ping)
		other.POST("/talk/reply/delete", api.Ping)
		other.POST("/talk/up", api.Ping)
	}
	return r
}
